# Example Usage of https://gitlab.msu.edu/msu-libraries/public/cicd-templates/Git.gitlab-ci.yml,
# refer there for detailed usage instructions.

include:
  - project: 'msu-libraries/public/cicd-templates'
    ref: main
    file: 'Git.gitlab-ci.yml'

stages:
  - Deploy

default:
  tags:
    - my-gitlab-runner-tag # required for non-MSU Library users
  variables:
    USER: "deploy"
    ENCODED_PRIVATE_KEY: $CI_VAR_WITH_ENCODED_PRIVATE_SSH_KEY
    REPO_PATH: "/home/deploy/repo/path"

# Example overriding the when parameter to auto deploy to devel if the previous stage passed
1 Deploy Devel:
  variables:
    SERVER: "server.devel.lib.msu.edu"
  when: on_success

2 Deploy Stage:
  variables:
    SERVER: "server.stage.lib.msu.edu"

3 Deploy Prod:
  variables:
    SERVER: "server.lib.msu.edu"
  
# Note that Deploy Prod Alt is excluded and will not be in the pipeline
